-- =========================================
-- 000_prereq_roles_warehouses.sql
-- 初始化：角色、数据库/Schema、仓库、资源监控器（RM_DAY）、授权
-- =========================================

-- 统一使用 UTC，避免延迟统计偏差
ALTER SESSION SET TIMEZONE='UTC';

-- ---------- 参数（可修改） ----------
SET DB_NAME   = 'DEMO_DW';
SET WH_NAME   = 'WH_TINY';
SET RM_NAME   = 'RM_DAY';
SET RAW_SCHEMA  = 'RAW';
SET MART_SCHEMA = 'MART';
SET MON_SCHEMA  = 'MART_MON';

-- 角色（最小集）
SET ROLE_CONNECT = 'CONNECT_ROLE';   -- 给 Kafka Connect 使用（只写 RAW）
SET ROLE_MART    = 'MART_ROLE';      -- 解析/任务角色（读 RAW、写 MART/MART_MON）

USE ROLE ACCOUNTADMIN;

-- ---------- 角色 ----------
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_CONNECT);
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_MART);

-- （按需）把解析/任务角色授予你自己，便于执行下面 DDL
-- GRANT ROLE IDENTIFIER($ROLE_MART) TO USER <YOUR_USER>;

-- ---------- 数据库与 Schema ----------
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DB_NAME) COMMENT='Streaming demo DB';
CREATE SCHEMA   IF NOT EXISTS IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($RAW_SCHEMA);
CREATE SCHEMA   IF NOT EXISTS IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MART_SCHEMA);
CREATE SCHEMA   IF NOT EXISTS IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MON_SCHEMA);

-- ---------- Resource Monitor （按日重置） ----------
-- 说明：仅通知，不自动停仓；可按需把 100% 改为 DO SUSPEND
CREATE OR REPLACE RESOURCE MONITOR IDENTIFIER($RM_NAME)
  WITH CREDIT_QUOTA = 20
  FREQUENCY = DAILY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO NOTIFY;

-- ---------- Warehouse ----------
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WH_NAME)
  WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND   = 300
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE
    RESOURCE_MONITOR = IDENTIFIER($RM_NAME);

-- ---------- 最小授权 ----------
-- 给 CONNECT_ROLE：仅能写 RAW（以及使用仓库）
GRANT USAGE ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_CONNECT);
GRANT USAGE ON SCHEMA   IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($RAW_SCHEMA) TO ROLE IDENTIFIER($ROLE_CONNECT);
GRANT INSERT ON ALL TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($RAW_SCHEMA) TO ROLE IDENTIFIER($ROLE_CONNECT);
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH_NAME) TO ROLE IDENTIFIER($ROLE_CONNECT);

-- 给 MART_ROLE：读 RAW，写 MART/MART_MON
GRANT USAGE ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_MART);
GRANT USAGE ON SCHEMA   IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($RAW_SCHEMA)   TO ROLE IDENTIFIER($ROLE_MART);
GRANT USAGE ON SCHEMA   IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MART_SCHEMA)  TO ROLE IDENTIFIER($ROLE_MART);
GRANT USAGE ON SCHEMA   IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MON_SCHEMA)   TO ROLE IDENTIFIER($ROLE_MART);

GRANT SELECT ON ALL TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($RAW_SCHEMA)  TO ROLE IDENTIFIER($ROLE_MART);
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MART_SCHEMA) TO ROLE IDENTIFIER($ROLE_MART);
GRANT CREATE TABLE, CREATE VIEW, CREATE TASK, CREATE STREAM
      ON SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MON_SCHEMA) TO ROLE IDENTIFIER($ROLE_MART);

-- （未来有新表时仍需授权：可以加未来授权）
GRANT INSERT, UPDATE, DELETE, SELECT
  ON FUTURE TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MART_SCHEMA) TO ROLE IDENTIFIER($ROLE_MART);
GRANT INSERT, UPDATE, DELETE, SELECT
  ON FUTURE TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($MON_SCHEMA)  TO ROLE IDENTIFIER($ROLE_MART);

-- 切到解析/任务角色 + 仓库，用于后续脚本
USE ROLE IDENTIFIER($ROLE_MART);
USE WAREHOUSE IDENTIFIER($WH_NAME);
USE DATABASE IDENTIFIER($DB_NAME);
